### ISSUE TITLE
java.lang.NoClassDefFoundError: main/Main in eta-init project

### ISSUE THREAD

**Issue by jneira** [typelead/gradle-eta#20]
Hi, after downloading the eta-init project and changing the plugin version to 0.6.5, a `.\gradlew run` throws this error:

```
Exception in thread "main" java.lang.NoClassDefFoundError: main/Main
        at eta.main.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException: main.Main
        at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 1 more
```

The build.gradle is:
```groovy
plugins {
    id 'com.typelead.eta' version '0.6.5'
    id 'application'
}

eta {
    version = '0.7.2b1'
    etlasVersion = '1.3.0.0'
}

dependencies {
  compile eta('base:4.8.2.0')
}
```
Same for 0.6.4 version, both tested in windows 10

**Comment by jneira** [comment]
* gradle-eta\examples\simple works fine
* gradle-eta\examples\simple multi fails with the same error that eta-init

**Comment by jneira** [comment]
* After upgrade to 0.6.6 the error persists

**Comment by jneira** [comment]
* As anticipated by @rahulmutt, the error is not thrown if removing `module Main where ` from `Main.hs`
